### PR TITLE
Updating to cocoapods 1.0

### PR DESCRIPTION
**Pull request by hfossli**

### CODE REVIEW

**Comment by hfossli** [comment]
I don't know if this is sufficient. It seemed to work for me with the following setup
1. Installed cocoapods 1.0 with `gem install cocoapods`
2. Installed the gem locally with `gem build cocoapods_links.gemspec && gem install --local cocoapods-links`
3. Run `pod link` and `pod link xxx`

**Comment by hfossli** [comment]
Will it work with the cococapods app? I have so many questions in my head about the plugins architecture.

**Comment by hfossli** [comment]
Please give me some feedback on this.

**Comment by hfossli** [comment]
Bump 😀

**Comment by hfossli** [comment]
hello :)

**Comment by hfossli** [comment]
To install

```
cd $(mktemp -d) && git clone git@github.com:hfossli/cocoapods-links.git && cd cocoapods-links && sudo gem build cocoapods_links.gemspec && gem install --local cocoapods-links && cd .. && rm -rf `pwd` 
```

**Comment by mowens** [comment]
Sorry all. I haven't been able to be attentive to this.

**Comment by hfossli** [comment]
No problem. :) Would be awesome if you can publish this :)

**Pull request merged**
